export class Media {
    date: string;
    date_gmt: string;
    guid: any;
    id: number;
    link: string;
    modified: string;
    modified_gmt: string;
    slug: string;
    status: string;
    type: string;
    permalink_template: string;
    generated_slug: string;
    title: any;
    author: number;
    comment_status: string;
    ping_status: string;
    meta: any;
    template: string;
    alt_text: string;
    caption: any;
    description: any;
    media_type: string;
    mime_type: string;
    media_details: any;
    post: number;
    source_url: string;
    missing_image_sizes: [];
}