export class Post {
    date: string;
    date_gmt: string;
    guid: any;
    id: number;
    link: string;
    modified: string;
    modified_gmt: string;
    slug: string;
    status: string;
    type: string;
    password: string;
    permalink_template: string;
    generated_slug: string;
    title: any;
    content: any;
    author: number;
    excerpt: any;
    rendered: string;
    featured_media: number;
    comment_status: string;
    ping_status: string;
    format: string;
    meta: any;
    sticky: boolean;
    template: string;
    categories: [];
    tags: [];
}